#!/usr/bin/env bash
# Squash the current branch to its merge base, and commit using provided commit message.

set -e

red='\033[0;31m'
cyan='\033[0;36m'
nc='\033[0m'

function print_usage {
    echo "Usage:"
    echo "  squash-branch [base-branch] \"commit-message\""
    echo
    echo "  base-branch defaults to 'master'"
} 


if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo
    echo -e "${red}Error ${nc}- Wrong number of arguments"
    echo
    print_usage
    echo
    exit 1
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [[ $# -eq 1 ]]; then
    base_branch=master
    message=$1
fi

if [[ $# -eq 2 ]]; then
    base_branch=$1
    message=$2
fi

echo -e "Current branch: ${cyan}$current_branch"
echo -e "Base branch:    ${cyan}$base_branch"

git reset $(git merge-base $base_branch $current_branch)
git add -A
git commit -m "$message"
